Repository googleapis/java-accessapproval, pull requests merged in 2020-08, with the labels that each got.

#150 docs: replace html with markdown for accessapproval.proto
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalSettings.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalSettingsOrBuilder.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessLocations.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessLocationsOrBuilder.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessReason.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/EnrolledService.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/EnrolledServiceOrBuilder.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/ListApprovalRequestsMessage.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/ListApprovalRequestsMessageOrBuilder.java
  proto-google-cloud-accessapproval-v1/src/main/proto/google/cloud/accessapproval/v1/accessapproval.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#152 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#153 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#156 feat: promote to 1.0.0
  .repo-metadata.json
  README.md
Labels: cla: yes

#161 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#163 chore(java_templates): add lint/static analysis presubmit checks for samples
  .github/workflows/samples.yaml
  synth.metadata
Labels: cla: yes, context: full

#166 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#167 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: accessapproval, cla: yes, context: full

#168 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
