Repository googleapis/java-accessapproval, pull requests merged in 2020-05, with the labels that each got.

#91 ci(java): switch to GitHub Actions (#533)
  .github/workflows/ci.yaml
  .kokoro/build.bat
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#94 chore: regenerate README versions
  README.md
  synth.metadata
Labels: cla: yes, context: none

#102 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: automerge, cla: yes

#101 Revert "changes without context (#94)"
  README.md
  synth.metadata
Labels: automerge, cla: yes

#98 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none
