Repository googleapis/java-accessapproval, pull requests merged in 2020-12, with the labels that each got.

#279 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#278 chore: migrate to the microgenerator
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalAdminClient.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalAdminSettings.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/package-info.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/stub/AccessApprovalStub.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/stub/AccessApprovalStubSettings.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/stub/GrpcAccessApprovalCallableFactory.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/stub/GrpcAccessApprovalStub.java
  google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/AccessApprovalAdminClientTest.java
  google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/MockAccessApproval.java
  google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/MockAccessApprovalImpl.java
  proto-google-cloud-accessapproval-v1/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalProto.java
  proto-google-cloud-accessapproval-v1/src/main/proto/google/cloud/accessapproval/v1/accessapproval.proto
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#282 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#283 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#281 samples: add quickstart sample and integration tests
  google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/it/ITAccessApprovalTest.java
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/accessapproval/Quickstart.java
  samples/snippets/src/test/java/accessapproval/QuickstartIT.java
Labels: api: accessapproval, automerge, cla: yes, samples

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#286 chore: migrate to microgenerator
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/AccessApprovalAdminClient.java
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/stub/GrpcAccessApprovalStub.java
  google-cloud-accessapproval/src/test/java/com/google/cloud/accessapproval/v1/AccessApprovalAdminClientTest.java
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#295 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#296 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#297 chore: update gapic-generator-java to 0.0.13
  google-cloud-accessapproval/src/main/java/com/google/cloud/accessapproval/v1/package-info.java
  synth.metadata
Labels: api: accessapproval, cla: yes, context: full

#299 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#300 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full, merge
