Repository googleapis/java-accessapproval, pull requests merged in 2020-09, with the labels that each got.

#174 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: accessapproval, cla: yes, context: full

#175 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#188 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#190 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#191 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: accessapproval, automerge, cla: yes

#198 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#200 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
