Repository googleapis/java-accessapproval, pull requests merged in 2021-05, with the labels that each got.

#416 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: none

#420 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: accessapproval, automerge, cla: yes

#421 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#425 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#429 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#431 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#432 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#434 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: accessapproval, automerge, cla: yes, context: full

#440 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes

#444 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: accessapproval, automerge, cla: yes
