Repository googleapis/java-accessapproval, pull requests merged in 2021-09, with the labels that each got.

#558 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: accessapproval, automerge

#562 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: accessapproval, automerge

#588 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: accessapproval
